name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar checkout do projeto
        uses: actions/checkout@v4

      - name: Autenticar Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da Imagem Docker
        run: echo "Executando o comando DOCKER BUILD"

      - name: Envio da Imagem Docker
        run: echo "Executando o comando DOCKER PUSH"


  cd-eks:
    runs-on: ubuntu-latest
    needs: [ci-docker]
    steps:
      - name: Autenticação na AWS
        run: echo "Executando o comando AWS CONFIGURE"

      - name: Configurar o kubectl
        run: echo "Executando o comando AWS EKS UPDATE-KUBECONFIG"

      - name: Deploy dos manifestos
        run: echo "Executando o comando KUBECTL APPLY"
