name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar checkout do projeto
        uses: actions/checkout@v4

      - name: Autenticar Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push Docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: src/Dockerfile
          tags: |
            debarbozar/fake-shop:latest
            debarbozar/fake-shop:v${{github.run_number}}


  cd-eks:
    runs-on: ubuntu-latest
    needs: [ci-docker]
    steps:
      - name: Realizar checkout do projeto
        uses: actions/checkout@v4
      
      - name: Autenticação na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configurar o kubectl
        run: echo "Executando o comando AWS EKS UPDATE-KUBECONFIG"

      - name: Deploy dos manifestos
        run: echo "Executando o comando KUBECTL APPLY"
